ALTER TABLE scheduled_test_plans
    ADD COLUMN IF NOT EXISTS test_prompt TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS expected_answer TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS reasoning_effort VARCHAR(16) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS judge_group_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS judge_model_id VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS judge_prompt TEXT NOT NULL DEFAULT '';

ALTER TABLE scheduled_test_results
    ADD COLUMN IF NOT EXISTS quality_verdict VARCHAR(16) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS quality_reason TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS judge_account_id BIGINT NOT NULL DEFAULT 0;
